### ISSUE TITLE
argument_wrong_length with fragment

### ISSUE THREAD

**Issue by jjcarstens** [elixir-sqlite/exqlite#156]
Via `exqlite 0.6.1`

This could be a case of _"I dont know what I'm doing"_, but I can't seem to get past this error when trying to us a fragment and pinned variable in a query:

```elixir
fc = 101
len = 26
query = 
  from(
    cf in C,
    where: c.fc == ^fc and fragment("format LIKE '%?%'", ^len)
  )

Repo.all(query)
```

Error:

```
15:50:26.087 [debug] QUERY ERROR source="cs" db=0.0ms queue=0.1ms idle=1824.6ms
SELECT c0."id", c0."fc", c0."format", FROM "cs" AS c0 WHERE ((c0."fc" = ?) AND format LIKE '%?%') [101, 26]
** (Exqlite.Error) arguments_wrong_length
SELECT c0."id", c0."fc", c0."format" FROM "cs" AS c0 WHERE ((c0."fc" = ?) AND format LIKE '%?%')
    (ecto_sql 3.6.2) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.6.2) lib/ecto/adapters/sql.ex:693: Ecto.Adapters.SQL.execute/5
    (ecto 3.6.2) lib/ecto/repo/queryable.ex:224: Ecto.Repo.Queryable.execute/4
    (ecto 3.6.2) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
```

But if I hardcode the values, it works:

```elixir
iex()> query = 
...()>   from(
...()>    cf in C,
...()>    where: c.fc == 101 and fragment("format LIKE '%?%'", 26)
...()>  )

iex()> Repo.all(query)
[
  %C{
    __meta__: #Ecto.Schema.Metadata<:loaded, "cs">,
    fc: 101,
    format: "this has 26 in the format",
    id: 2
  }
]
```

**Comment by kevinlang** [comment]
Can you try

```
fc = 101
len = "%26%"
query = 
  from(
    cf in C,
    where: c.fc == ^fc and fragment("format LIKE ?", ^len)
  )

Repo.all(query)
```

I think that will work.

https://stackoverflow.com/questions/24462631/how-to-use-in-sqlite-prepared-statements-for-android

**Comment by kevinlang** [comment]
Alternatively I think you can do something like

```
format LIKE "%" || ? || "%"
```

Not sure though. Essentially SQLite is not going to inject the parameter into any string directly.
